export const OFFER_LIST_ADD = "OFFER_LIST_ADD";
export const OFFER_LIST_ERROR = "OFFER_LIST_ERROR";
export const OFFER_LIST_RECEIVE = "OFFER_LIST_RECEIVE";
export const OFFER_LIST_REQUEST = "OFFER_LIST_REQUEST";


export const PROFIL_LIST_ADD = "PROFIL_LIST_ADD";
export const PROFIL_LIST_ERROR = "PROFIL_LIST_ERROR";
export const PROFIL_LIST_RECEIVE = "PROFIL_LIST_RECEIVE";
export const PROFIL_LIST_REQUEST = "PROFIL_LIST_REQUEST";




export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_COMPLETED = "USER_REGISTER_COMPLETED";
export const USER_CONFIRMATION_SUCCESS = "USER_CONFIRMATION_SUCCESS";

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_PROFILE_ERROR = "USER_PROFILE_ERROR";

export const USER_PROFILE_RECEIVED = "USER_PROFILE_RECEIVED";
export const USER_SET_ID = "USER_SET_ID";
